// Cloudflare Worker entry: OpenNext's generated handler plus a short-lived page cache.
//
// The free plan allows 10 ms of CPU per request, and rendering a large public page (home, coverage, PYQ hubs) uses
// most of it. A burst of visitors or crawlers asking for the same URLs then hits "Worker exceeded resource limits"
// (1102). Anonymous full-page GETs are therefore kept in this isolate's memory for a minute. Everything personal or
// interactive is never cached: the admin (and anyone signed in to it), API routes, tests, results, papers, and React
// Server Component requests made by client-side navigation. Admin actions clear this cache along with the shared
// cache (see src/lib/data/shared-cache.ts); other isolates catch up within a minute.

// @ts-expect-error -- generated by `opennextjs-cloudflare build`, untyped.
import openNext from "./.open-next/worker.js";

type Handler = { fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> };
type Entry = { at: number; body: ArrayBuffer; headers: [string, string][] };

const TTL_MS = 60_000;
const MAX_ENTRIES = 60;
const MAX_BYTES = 512 * 1024;
const NEVER = /^\/(admin|api|test|results|paper|_next|cdn-cgi)(\/|$)/;

const g = globalThis as { __erPageCache?: Map<string, Entry> };
const pages = (g.__erPageCache ??= new Map<string, Entry>());
const next = openNext as Handler;

function cacheable(request: Request, url: URL) {
  if (request.method !== "GET" || NEVER.test(url.pathname)) return false;
  if ((request.headers.get("cookie") ?? "").includes("er_admin=")) return false;
  // Client-side navigations fetch an RSC payload for the same URL; those vary by router state.
  if (request.headers.has("rsc") || request.headers.has("next-router-state-tree") || url.searchParams.has("_rsc")) return false;
  return true;
}

const worker = {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    if (!cacheable(request, url)) return next.fetch(request, env, ctx);

    const key = url.pathname + url.search;
    const hit = pages.get(key);
    if (hit && Date.now() - hit.at < TTL_MS) {
      const headers = new Headers(hit.headers);
      headers.set("x-er-cache", "hit");
      return new Response(hit.body, { status: 200, headers });
    }
    if (hit) pages.delete(key);

    const response = await next.fetch(request, env, ctx);
    const type = response.headers.get("content-type") ?? "";
    if (response.status === 200 && type.startsWith("text/html") && !response.headers.has("set-cookie")) {
      const copy = response.clone();
      ctx.waitUntil(
        copy
          .arrayBuffer()
          .then((body) => {
            if (body.byteLength > MAX_BYTES) return;
            // A streamed page commits its 200 status before rendering finishes, so a render error (database down,
            // query failure) still arrives as 200 with React's error markers in the HTML. Never keep those.
            const html = new TextDecoder().decode(body);
            if (html.includes("data-dgst") || html.includes("$RX(") || html.includes("couldn&#x27;t load") || html.includes("couldn't load")) return;
            if (pages.size >= MAX_ENTRIES) pages.delete(pages.keys().next().value as string);
            pages.set(key, { at: Date.now(), body, headers: [...copy.headers] });
          })
          .catch(() => {}),
      );
    }
    return response;
  },
};

export default worker;
