// Builds drizzle/seed/seed.sql from the demo question banks in src/data/demo/*.json.
//
// The demo bank was written by AI for demonstration. Every question is stored as
// AI_SUPPLEMENTARY, unreviewed, is_demo = 1, with no source paper, no year and no frequency.
// The UI always labels it "DEMO DATA — NOT A VERIFIED PREVIOUS-YEAR QUESTION".
//
// The seed is idempotent and only touches demo rows: taxonomy is upserted, demo questions
// (and generated papers built from them) are replaced. Real questions and source papers are kept.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { boardIdSql, chapterIdSql, classIdSql, contentHash, q, subjectIdSql, taxonomySql, upsertChapter, upsertSubject, upsertTopic } from "./lib/sql.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dataDir = join(root, "src", "data", "demo");
const outFile = join(root, "drizzle", "seed", "seed.sql");

const files = readdirSync(dataDir).filter((f) => f.endsWith(".json")).sort();
if (!files.length) {
  console.error("No demo data found in src/data/demo");
  process.exit(1);
}

const tax = JSON.parse(readFileSync(join(root, "src", "data", "taxonomy.json"), "utf8"));
const out = ["-- Generated by scripts/build-seed.mjs. Do not edit by hand."];

// Remove previous demo content only.
out.push("DELETE FROM generated_papers WHERE has_demo = 1;");
out.push("DELETE FROM question_sources WHERE question_id IN (SELECT id FROM questions WHERE is_demo = 1);");
out.push("UPDATE import_items SET duplicate_of_question_id = NULL WHERE duplicate_of_question_id IN (SELECT id FROM questions WHERE is_demo = 1);");
out.push("DELETE FROM questions WHERE is_demo = 1;");
out.push("DELETE FROM papers WHERE is_demo = 1;");

// Taxonomy first (boards, classes, subjects), then the ICSE 8–10 chapters that the demo bank defines.
out.push(...taxonomySql(tax));

const subjectOrder = tax.subjectOrder;
const stats = [];
for (const f of files) {
  const data = JSON.parse(readFileSync(join(dataDir, f), "utf8"));
  const { board, class: level } = data;
  const subj = data.subject.slug;
  out.push(upsertSubject(board, level, subj, data.subject.name, data.subject.overview, data.subject.studyTips, (subjectOrder.indexOf(subj) + 1) || 9));
  for (const ch of data.chapters) {
    out.push(upsertChapter(board, level, subj, ch, ch.order));
    ch.topics.forEach((tp, i) => out.push(upsertTopic(board, level, subj, ch.slug, tp, i + 1)));
  }
  for (const item of data.questions) {
    let answerKey = null;
    let options = null;
    if (item.type === "MCQ") {
      options = JSON.stringify(item.options);
      answerKey = JSON.stringify({ correctOption: item.correctOption });
    } else if (item.type === "FILL_BLANK") {
      answerKey = JSON.stringify({ accepted: item.acceptedAnswers });
    } else if (item.type === "NUMERICAL") {
      answerKey = JSON.stringify({ value: item.numericAnswer, tolerance: item.tolerance ?? 0, unit: item.unit ?? "" });
    }
    const topicSql = `(SELECT id FROM topics WHERE slug = ${q(item.topic)} AND chapter_id = ${chapterIdSql(board, level, subj, item.chapter)})`;
    out.push(
      `INSERT INTO questions (external_key, board_id, class_id, subject_id, chapter_id, topic_id, question_text, question_type, marks, difficulty, options, answer_key, answer_text, explanation, source_type, verification_status, verification_notes, is_published, is_demo, frequency_count, content_hash, mapping_status, mapping_source, answer_source) VALUES (${q(
        item.key,
      )}, ${boardIdSql(board)}, ${classIdSql(board, level)}, ${subjectIdSql(board, level, subj)}, ${chapterIdSql(board, level, subj, item.chapter)}, ${topicSql}, ${q(
        item.text,
      )}, ${q(item.type)}, ${item.marks}, ${q(item.difficulty)}, ${q(options)}, ${q(answerKey)}, ${q(item.answer ?? "")}, ${q(
        item.explanation ?? "",
      )}, 'AI_SUPPLEMENTARY', 'UNVERIFIED', ${q(
        "Demo question written by AI for demonstration. Not a previous-year question and not reviewed by an editor.",
      )}, 1, 1, 0, ${q(contentHash(item.text))}, 'CONFIRMED', 'author', 'AI');`,
    );
  }
  stats.push({ file: `${board} class ${level} ${subj}`, questions: data.questions.length });
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out.join("\n") + "\n", "utf8");
console.table(stats);
console.log(`Wrote ${outFile}`);
