// Builds drizzle/seed/sources.sql from the official source packs in src/data/sources/*.json.
//
// Every question starts UNVERIFIED and unpublished (extraction is not verification). An editor
// verifies and publishes it in /admin/review after checking it against the official document.
//
// Idempotent and non-destructive: source papers are upserted by source_key, questions are
// inserted once by external_key and never overwritten, so review decisions survive a re-run.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { boardIdSql, chapterIdSql, classIdSql, contentHash, q, similarity, subjectIdSql, taxonomySql } from "./lib/sql.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "src", "data", "sources");
const outFile = join(root, "drizzle", "seed", "sources.sql");

const TYPE_MAP = { MCQ: "MCQ", ASSERTION_REASON: "ASSERTION_REASON", SHORT_ANSWER: "SHORT_ANSWER", LONG_ANSWER: "LONG_ANSWER", CASE_BASED: "CASE_BASED", NUMERICAL: "NUMERICAL" };
const SOURCE_TYPE = { BOARD_EXAM: "VERIFIED_PYQ", SPECIMEN: "OFFICIAL_SAMPLE", SAMPLE: "OFFICIAL_SAMPLE", SCHOOL_EXAM: "USER_CONTRIBUTED", OTHER: "PENDING_REVIEW" };

const tax = JSON.parse(readFileSync(join(root, "src", "data", "taxonomy.json"), "utf8"));
const packs = readdirSync(dir)
  .filter((f) => f.endsWith(".json"))
  .sort()
  .map((f) => ({ file: f, ...JSON.parse(readFileSync(join(dir, f), "utf8")) }));

const out = ["-- Generated by scripts/build-sources.mjs. Do not edit by hand.", ...taxonomySql(tax)];
const problems = [];
const all = []; // for duplicate detection across packs

for (const pack of packs) {
  const s = pack.source;
  const { board, class: level, subject } = s;
  const domain = (() => {
    try {
      return new URL(s.sourceUrl).hostname;
    } catch {
      return null;
    }
  })();
  const cols = {
    board_id: boardIdSql(board),
    class_id: classIdSql(board, level),
    subject_id: subjectIdSql(board, level, subject),
    title: q(s.title),
    year: q(s.examYear ?? null),
    paper_type: q(s.paperType),
    source_url: q(s.sourceUrl ?? null),
    source_notes: q(s.notes ?? ""),
    is_demo: "0",
    source_key: q(s.key),
    authority: q(s.authority ?? "OTHER"),
    authority_name: q(s.authorityName ?? null),
    source_domain: q(domain),
    source_file: q(s.sourceFile ?? null),
    answer_source_url: q(s.answerSourceUrl ?? null),
    answer_source_file: q(s.answerSourceFile ?? null),
    exam_session: q(s.session ?? null),
    paper_name: q(s.paperName ?? null),
    paper_code: q(s.paperCode ?? null),
    set_code: q(s.setCode ?? null),
    series_code: q(s.seriesCode ?? null),
    region: q(s.region ?? null),
    language: q(s.language ?? null),
    file_type: q(s.fileType ?? null),
    page_count: q(s.pageCount ?? null),
    sha256: q(s.sha256 ?? null),
    max_marks: q(s.maxMarks ?? null),
    duration_minutes: q(s.durationMinutes ?? null),
    extraction_method: q(s.extractionMethod ?? null),
    extraction_tool: q(s.extractionTool ?? null),
    ocr_used: s.ocrUsed ? "1" : "0",
    status: "'PENDING_REVIEW'",
  };
  const names = Object.keys(cols);
  const updatable = names.filter((n) => !["status", "source_key", "is_demo"].includes(n));
  out.push(
    `INSERT INTO papers (${names.join(", ")}) SELECT ${names.map((n) => cols[n]).join(", ")} WHERE ${cols.subject_id} IS NOT NULL ON CONFLICT(source_key) DO UPDATE SET ${updatable
      .map((n) => `${n} = excluded.${n}`)
      .join(", ")};`,
  );
  const paperId = `(SELECT id FROM papers WHERE source_key = ${q(s.key)})`;

  for (const item of pack.questions) {
    const key = `${s.key}#${item.number}${item.part ? item.part.replace(/[^a-z0-9ivx]/gi, "") : ""}`;
    if (!item.chapter) {
      problems.push(`${key}: no chapter suggestion; skipped until mapped`);
      continue;
    }
    const type = TYPE_MAP[item.type];
    if (!type) {
      problems.push(`${key}: unknown type ${item.type}`);
      continue;
    }
    const hasOptions = Array.isArray(item.options) && item.options.length >= 2;
    const correct = item.officialAnswer && Number.isInteger(item.officialAnswer.correctOption) ? item.officialAnswer.correctOption : null;
    const answerKey = (type === "MCQ" || type === "ASSERTION_REASON") && hasOptions && correct !== null ? JSON.stringify({ correctOption: correct }) : null;
    const issues = [...(item.extractionIssues ?? [])];
    if ((type === "MCQ" || type === "ASSERTION_REASON") && !hasOptions) issues.push("Options were not extractable as text (see the source page).");
    const noteParts = [`Extracted from ${s.title}, page ${item.page}.`];
    if (item.choiceGroup) noteParts.push(`Internal choice: alternative ${item.part ?? ""} of question ${item.choiceGroup}.`);
    noteParts.push("Awaiting editor verification against the official PDF.");
    const chId = chapterIdSql(board, level, subject, item.chapter);
    out.push(
      `INSERT INTO questions (external_key, board_id, class_id, subject_id, chapter_id, question_text, question_type, marks, difficulty, options, answer_key, answer_text, explanation, source_type, verification_status, verification_notes, is_published, is_demo, frequency_count, content_hash, mapping_status, mapping_source, answer_source, has_figure, extraction_confidence, extraction_issues) SELECT ${q(
        key,
      )}, ${boardIdSql(board)}, ${classIdSql(board, level)}, ${subjectIdSql(board, level, subject)}, ${chId}, ${q(item.text)}, ${q(type)}, ${item.marks}, 'UNRATED', ${q(
        hasOptions ? JSON.stringify(item.options) : null,
      )}, ${q(answerKey)}, ${q(item.officialAnswer?.text ?? "")}, '', ${q(SOURCE_TYPE[s.paperType] ?? "PENDING_REVIEW")}, 'UNVERIFIED', ${q(
        noteParts.join(" "),
      )}, 0, 0, 0, ${q(contentHash(item.text))}, 'SUGGESTED', 'ai', ${q(item.officialAnswer ? "OFFICIAL_SCHEME" : "NONE")}, ${item.hasFigure ? 1 : 0}, ${q(
        item.confidence ?? null,
      )}, ${q(JSON.stringify(issues))} WHERE ${chId} IS NOT NULL ON CONFLICT(external_key) DO NOTHING;`,
    );
    out.push(
      `INSERT INTO question_sources (question_id, paper_id, question_number, part, page_number, section, marks_in_paper, is_primary, notes) SELECT (SELECT id FROM questions WHERE external_key = ${q(
        key,
      )}), ${paperId}, ${q(String(item.number))}, ${q(item.part ?? null)}, ${q(item.page ?? null)}, ${q(
        [item.section, item.sectionTitle].filter(Boolean).join(" ") || null,
      )}, ${item.marks}, 1, ${q(item.marksSource === "SECTION_INSTRUCTIONS" ? "Marks taken from the section instructions." : "")} WHERE (SELECT id FROM questions WHERE external_key = ${q(
        key,
      )}) IS NOT NULL AND ${paperId} IS NOT NULL ON CONFLICT(question_id, paper_id) DO NOTHING;`,
    );
    all.push({ key, text: item.text, hash: contentHash(item.text), subject: `${board}/${level}/${subject}`, type });
  }
}

// Duplicate detection: exact normalised match, or near-identical wording, within a subject.
// The first occurrence (by pack order) is canonical. Existing canonical links are never overwritten.
let dupes = 0;
for (let i = 0; i < all.length; i++) {
  for (let j = 0; j < i; j++) {
    const a = all[j];
    const b = all[i];
    if (a.subject !== b.subject || a.key.split("#")[0] === b.key.split("#")[0]) continue;
    if (a.hash === b.hash || (a.type === b.type && similarity(a.text, b.text) >= 0.85)) {
      out.push(
        `UPDATE questions SET canonical_question_id = (SELECT COALESCE(canonical_question_id, id) FROM questions WHERE external_key = ${q(
          a.key,
        )}) WHERE external_key = ${q(b.key)} AND canonical_question_id IS NULL;`,
      );
      dupes++;
      break;
    }
  }
}

out.push(
  "UPDATE questions SET frequency_count = (SELECT COUNT(DISTINCT p.id) FROM question_sources qs JOIN papers p ON p.id = qs.paper_id WHERE qs.question_id = questions.id AND p.paper_type = 'BOARD_EXAM' AND p.is_demo = 0) WHERE is_demo = 0;",
);

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out.join("\n") + "\n", "utf8");
console.log(`[sources] ${packs.length} source packs, ${all.length} questions, ${dupes} duplicate links → ${outFile}`);
for (const p of problems) console.log(`[sources] ${p}`);
