// Builds drizzle/seed/seed.sql from the demo question banks in src/data/demo/*.json.
//
// Every question produced here is DEMO DATA (is_demo = 1). Demo questions are assigned
// stand-in source categories so every part of the product can be exercised, but they are
// linked only to fictional demo papers with no year, and the UI always labels them
// "DEMO DATA — NOT A VERIFIED PREVIOUS-YEAR QUESTION".
import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dataDir = join(root, "src", "data", "demo");
const outFile = join(root, "drizzle", "seed", "seed.sql");

const q = (v) => (v === null || v === undefined ? "NULL" : typeof v === "number" ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const b = (v) => (v ? 1 : 0);

function fnv(str) {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h;
}

/** Must match normaliseForHash in src/lib/text.ts */
function contentHash(text) {
  const norm = text.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, " ").trim();
  return createHash("sha1").update(norm).digest("hex");
}

const files = readdirSync(dataDir).filter((f) => f.endsWith(".json")).sort();
if (files.length === 0) {
  console.error("No demo data found in src/data/demo");
  process.exit(1);
}

const out = [];
out.push("-- Generated by scripts/build-seed.mjs. Do not edit by hand.");
for (const t of [
  "attempt_answers", "attempts", "paper_questions", "generated_papers", "import_items", "import_batches",
  "question_sources", "questions", "papers", "topics", "chapters", "subjects", "classes", "boards", "users",
]) out.push(`DELETE FROM ${t};`);

out.push(
  `INSERT INTO boards (id, slug, name, full_name, description, is_active, sort_order) VALUES (1, 'icse', 'ICSE', 'Indian Certificate of Secondary Education', ${q(
    "ICSE is conducted by the Council for the Indian School Certificate Examinations (CISCE). Its papers are known for detailed, application-based questions and a wide syllabus, especially in the sciences.",
  )}, 1, 1);`,
);

const classIds = { 8: 1, 9: 2, 10: 3 };
for (const [level, id] of Object.entries(classIds)) {
  out.push(`INSERT INTO classes (id, board_id, level, slug, name, is_active) VALUES (${id}, 1, ${level}, 'class-${level}', 'Class ${level}', 1);`);
}

const subjectOrder = ["mathematics", "physics", "chemistry", "biology"];
let subjectId = 0, chapterId = 0, topicId = 0, paperId = 0, questionId = 0, qsId = 0;
const stats = [];

const datasets = files.map((f) => JSON.parse(readFileSync(join(dataDir, f), "utf8")));
datasets.sort((a, b2) => a.class - b2.class || subjectOrder.indexOf(a.subject.slug) - subjectOrder.indexOf(b2.subject.slug));

for (const data of datasets) {
  const cls = classIds[data.class];
  if (!cls) throw new Error(`Unknown class ${data.class}`);
  const sid = ++subjectId;
  out.push(
    `INSERT INTO subjects (id, class_id, slug, name, overview, study_tips, sort_order) VALUES (${sid}, ${cls}, ${q(data.subject.slug)}, ${q(
      data.subject.name,
    )}, ${q(data.subject.overview)}, ${q(JSON.stringify(data.subject.studyTips ?? []))}, ${subjectOrder.indexOf(data.subject.slug) + 1});`,
  );

  const chapterMap = new Map();
  const topicMap = new Map();
  for (const ch of [...data.chapters].sort((a, b2) => a.order - b2.order)) {
    const cid = ++chapterId;
    chapterMap.set(ch.slug, cid);
    out.push(
      `INSERT INTO chapters (id, subject_id, slug, name, summary, sort_order) VALUES (${cid}, ${sid}, ${q(ch.slug)}, ${q(ch.name)}, ${q(ch.summary ?? "")}, ${ch.order});`,
    );
    ch.topics.forEach((tp, i) => {
      const tid = ++topicId;
      topicMap.set(`${ch.slug}/${tp.slug}`, tid);
      out.push(`INSERT INTO topics (id, chapter_id, slug, name, sort_order) VALUES (${tid}, ${cid}, ${q(tp.slug)}, ${q(tp.name)}, ${i + 1});`);
    });
  }

  // Fictional demo source papers: no year, clearly titled as demo.
  const demoBoardPapers = [];
  for (let n = 1; n <= 6; n++) {
    const pid = ++paperId;
    demoBoardPapers.push(pid);
    out.push(
      `INSERT INTO papers (id, board_id, class_id, subject_id, title, year, paper_type, source_url, source_notes, is_demo) VALUES (${pid}, 1, ${cls}, ${sid}, ${q(
        `Demo exam paper ${n} (fictional)`,
      )}, NULL, 'BOARD_EXAM', NULL, ${q("Fictional paper used only to demonstrate provenance and frequency features. Not a real examination.")}, 1);`,
    );
  }
  const specimenId = ++paperId;
  out.push(
    `INSERT INTO papers (id, board_id, class_id, subject_id, title, year, paper_type, source_url, source_notes, is_demo) VALUES (${specimenId}, 1, ${cls}, ${sid}, 'Demo specimen paper (fictional)', NULL, 'SPECIMEN', NULL, ${q(
      "Fictional specimen paper used only for demonstration. Not official material.",
    )}, 1);`,
  );

  // Class 8 banks are deliberately PYQ-light so the "insufficient verified questions" path can be demonstrated.
  const pyqShare = data.class === 8 ? 35 : 70;
  const counts = { VERIFIED_PYQ: 0, OFFICIAL_SAMPLE: 0, USER_CONTRIBUTED: 0, AI_SUPPLEMENTARY: 0 };

  for (const item of data.questions) {
    const qid = ++questionId;
    const h = fnv(item.key) % 100;
    const h2 = fnv(item.key + "#status") % 100;
    let sourceType, status;
    if (h < pyqShare) {
      sourceType = "VERIFIED_PYQ";
      status = "VERIFIED";
    } else if (h < pyqShare + 12) {
      sourceType = "OFFICIAL_SAMPLE";
      status = "VERIFIED";
    } else if (h < pyqShare + 22) {
      sourceType = "USER_CONTRIBUTED";
      status = h2 < 50 ? "VERIFIED" : "UNVERIFIED";
    } else {
      sourceType = "AI_SUPPLEMENTARY";
      status = h2 < 75 ? "VERIFIED" : "UNVERIFIED";
    }
    counts[sourceType]++;

    const chId = chapterMap.get(item.chapter);
    if (!chId) throw new Error(`${item.key}: unknown chapter ${item.chapter}`);
    const tId = topicMap.get(`${item.chapter}/${item.topic}`) ?? null;

    let answerKey = null;
    let options = null;
    if (item.type === "MCQ") {
      options = JSON.stringify(item.options);
      answerKey = JSON.stringify({ correctOption: item.correctOption });
    } else if (item.type === "FILL_BLANK") {
      answerKey = JSON.stringify({ accepted: item.acceptedAnswers });
    } else if (item.type === "NUMERICAL") {
      answerKey = JSON.stringify({ value: item.numericAnswer, tolerance: item.tolerance ?? 0, unit: item.unit ?? "" });
    }

    // Demo PYQ stand-ins appear in 1–3 fictional demo papers so frequency analytics has stored data behind it.
    const links = [];
    if (sourceType === "VERIFIED_PYQ") {
      const appearances = 1 + (fnv(item.key + "#freq") % 3);
      const start = fnv(item.key + "#start") % demoBoardPapers.length;
      for (let k = 0; k < appearances; k++) links.push(demoBoardPapers[(start + k * 2) % demoBoardPapers.length]);
    } else if (sourceType === "OFFICIAL_SAMPLE") {
      links.push(specimenId);
    }
    const uniqueLinks = [...new Set(links)];
    const frequency = sourceType === "VERIFIED_PYQ" ? uniqueLinks.length : 0;
    const verifiedAt = status === "VERIFIED" ? "'2026-09-01T00:00:00.000Z'" : "NULL";

    out.push(
      `INSERT INTO questions (id, external_key, board_id, class_id, subject_id, chapter_id, topic_id, question_text, question_type, marks, difficulty, options, answer_key, answer_text, explanation, source_type, verification_status, verification_notes, verified_at, verified_by, is_published, is_demo, frequency_count, content_hash) VALUES (${qid}, ${q(
        item.key,
      )}, 1, ${cls}, ${sid}, ${chId}, ${q(tId)}, ${q(item.text)}, ${q(item.type)}, ${item.marks}, ${q(item.difficulty)}, ${q(options)}, ${q(answerKey)}, ${q(
        item.answer ?? "",
      )}, ${q(item.explanation ?? "")}, '${sourceType}', '${status}', ${q(
        "Demo data: category assigned for demonstration only.",
      )}, ${verifiedAt}, ${status === "VERIFIED" ? "'demo-seed'" : "NULL"}, 1, 1, ${frequency}, ${q(contentHash(item.text))});`,
    );
    uniqueLinks.forEach((pid, i) => {
      out.push(
        `INSERT INTO question_sources (id, question_id, paper_id, question_number, marks_in_paper, is_primary, notes) VALUES (${++qsId}, ${qid}, ${pid}, NULL, ${item.marks}, ${b(
          i === 0,
        )}, 'Demo link');`,
      );
    });
  }
  stats.push({ file: `class ${data.class} ${data.subject.slug}`, questions: data.questions.length, ...counts });
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out.join("\n") + "\n", "utf8");
console.table(stats);
console.log(`Wrote ${outFile}`);
